const newsData2 = [
  {
    text: "Rezolve Appoints Sauvik Banerjjee as Global CEO of Products, Technology, and Digital Services",

    img: "/yahoo.png",
    description: `Rezolve Appoints Sauvik Banerjjee as Global CEO of Products, Technology, and Digital Services`,
    date: "Aug 08, 2022",
    url: " https://finance.yahoo.com/news/rezolve-appoints-sauvik-banerjjee-global-113000405.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS8&guce_referrer_sig=AQAAAJna0VH1YQQ6i2gieaKnzaxgkfNQi439C84P4e7aGbt08O_1jnDLpg9569NHdZf5h3QMM1f_k0H4x8qP7ONhAodGAFOquh3KzumyqDLxndePkpS5_w2QFt8azwS8o6iuv3qj3KExNehUaO1wV9GwdaybaD3po3-J1cNV2fRfsh-6",
  },

  {
    "#": 4,
    date: "Aug 5, 2022",
    Source: "News Portal",
    "Channel Name": "outlookindia",
    img: "/outlook.png",
    url: "https:/www.outlookindia.com/business/tata-neu-cto-sauvik-banerjee-quits-news-214472",
    text: "Tata Neu CTO Sauvik Banerjee Quits",
    description:
      "Tata Neu, the 'super app' of the Tata Group, was launched in April this year. It is a part of Tata Digital, which the conglomerate set up to build its digital businesses",
  },

  {
    "#": 6,
    date: "Aug 5, 2022",
    Source: "News Portal",
    "Channel Name": "businesstoday",
    img: "/businessToday.png",
    url: "https:/www.businesstoday.in/technology/story/tata-neu-cto-sauvik-banerjjee-quits-343919-2022-08-05",
    text: "Tata Neu CTO Sauvik Banerjjee quits",
    description:
      "Tata Neu, the 'super app' of the Tata Group, was launched in April this year. It is a part of Tata Digital, which the conglomerate set up to build its digital businesses.",
  },

  {
    "#": 8,
    date: "Aug 09, 2022",
    Source: "News Portal",
    "Channel Name": "yourstory",
    img: "/yourstory.png",
    url: "https:/yourstory.com/2017/09/sauvik-banerjjee-cto-tata-cliq-ama",
    text: "“Leadership is all about empowering and extracting the performance without doing micromanagement” - Sauvik Banerjjee, CTO, Tata CLiQ\n",
  },
  {
    "#": 9,
    date: "Aug 09, 2022",
    Source: "News Portal",
    "Channel Name": "yourstory",
    img: "/yourstory.png",
    url: "https:/yourstory.com/2017/07/sauvik-banerjjee-cto-tatacliq-ai-ml",
    text: "AI, ML will be game-changers in online retail: Sauvik Banerjjee, CTO of TataCLiQ\n",
  },
  {
    "#": 10,
    date: "Aug 09, 2022",
    Source: "News Portal",
    "Channel Name": "yourstory",
    img: "/yourstory.png",
    url: "https:/yourstory.com/2017/03/techie-tuesdays-sauvik-banerjjee",
    text: "[Techie Tuesdays] Meet Sauvik Banerjjee, a Ranji trophy player who went on to architect Reliance Jio",
  },
  {
    "#": 11,
    date: "Aug 09, 2022",
    Source: "News Portal",
    "Channel Name": "techplusmedia",
    img: "/techplus.png",
    url: "https:/cxotv.techplusmedia.com/trending-news/rezolve-appoints-sauvik-banerjjee-as-global-chief-executive-of-products-technology-and-digital-services/",
    text: "Rezolve Appoints Sauvik Banerjjee as Global Chief Executive of Products, Technology and Digital Services",
  },
  {
    "#": 12,
    date: "Jul 28, 2022",
    Source: "News Portal",
    "Channel Name": "moneycontrol",
    img: "/moneyC.png",
    url: "https:/www.moneycontrol.com/news/business/tata-neus-cto-sauvik-banerjjee-quits-to-take-on-global-role-8908871.html",
    text: "Tata Neu’s CTO Sauvik Banerjjee quits, to take on global role",
    description:
      "Prior to joining Neu in 2019, Banerjjee worked as the CTO of Tata Cliq. He joined the group in 2016 and extensively worked with TCS.",
  },
  {
    "#": 13,
    date: "Oct 16, 2017",
    Source: "News Portal",
    "Channel Name": "getbengal",
    img: "/getBengal.png",
    url: "https:/www.getbengal.com/details/world-renowned-bengali-techie-brings-projects-to-bengal",
    text: "World-renowned Bengali techie brings projects to Bengal",
  },
  {
    "#": 14,
    date: "Jul 29, 2022",
    Source: "News Portal",
    "Channel Name": "bwdisrupt",
    img: "/bw.png",
    url: "https:/bwdisrupt.businessworld.in/article/Tata-Neu-s-CTO-Sauvik-Banerjjee-Resigns-/29-07-2022-439368/",
    text: "Tata Neu’s CTO Sauvik Banerjjee Resigns",
    description:
      "According to media reports, Banerjjee has decided to take on a role abroad after moving on from Tata Neu",
  },

  {
    "#": 16,
    date: "Jul 29, 2022",
    Source: "News Portal",
    "Channel Name": "cionews",
    img: "/cioNews.png",
    url: "https:/cionews.co.in/cto-sauvik-banerjjee-quits-tata-neu/",
    text: "CTO Sauvik Banerjjee quits Tata Neu four months after launch",
  },
  {
    "#": 17,
    date: "Jul 29, 2022",
    Source: "News Portal",
    "Channel Name": "startupstorymedia",
    img: "/yourstory.png",
    url: "https:/startupstorymedia.com/insights-tata-neu-cto-sauvik-banerjjee-resigns-external-hire-likely-to-fill-the-position/",
    text: "Tata Neu CTO Sauvik Banerjjee Resigns, External Hire Likely To Fill The Position",
  },
  {
    "#": 18,
    date: "Aug 8, 2022",
    Source: "News Portal",
    "Channel Name": "msn",
    img: "/msn.png",
    url: "https:/www.msn.com/en-in/money/topstories/corporate-crossings-tata-neu-s-former-cto-sauvik-banerjjee-joins-uk-firm-rezolve-as-ceo/ar-AA10r7wC",
    text: "Corporate Crossings | Tata Neu's former CTO Sauvik Banerjjee joins UK firm Rezolve as CEO",
  },
  {
    "#": 19,
    date: "Aug 8, 2022",
    Source: "News Portal",
    "Channel Name": "finance.yahoo.com",
    img: "/yahoo.png",
    url: "https:/finance.yahoo.com/news/rezolve-appoints-sauvik-banerjjee-global-113000405.html",
    text: "Rezolve Appoints Sauvik Banerjjee as Global CEO of Products, Technology, and Digital Services",
  },
  {
    "#": 20,
    date: "Jul 9, 2022",
    Source: "News Portal",
    "Channel Name": "forbesindia",
    img: "/fobes.png",
    url: "https:/www.forbesindia.com/audio/forbes-india-daily-tech-conver-sation/the-big-picture-sauvik-banerjjee-at-tata-digital-and-anand-chandrasekaran-at-mad-street-den-on-whither-personalisation/77129",
    text: "The Big Picture: Sauvik Banerjjee at Tata Digital and Anand Chandrasekaran at Mad Street Den on 'whither personalisation'",
    description:
      "Our guests today are Sauvik Banerjjee, founding CTO of Tata Digital, and Anand Chandrasekaran, co-founder and CTO of Mad Street Den, whose AI platform blox.ai plays an important role in the personalisation features of the Tata Group's new consumer app, Tata Neu. In this episode, Sauvik and Anand talk about bringing the power of AI to the evergreen quest for understanding the individual consumer's behaviour more intimately. They also have a non-techie piece of advice for aspiring CTOs",
  },
  {
    "#": 21,
    date: "Jul 27, 2022",
    Source: "News Portal",
    "Channel Name": "varindia.com",
    img: "/varindia.png",
    url: "https:/varindia.com/news/sauvik-banerjjee-resigns-as-tata-neus-cto",
    text: "Sauvik Banerjjee resigns as Tata Neu’s CTO",
  },
  {
    "#": 22,
    date: "Aug 5, 2022",
    Source: "News Portal",
    "Channel Name": "newsdrum",
    img: "/drum.png",
    url: "https:/www.newsdrum.in/business/tata-neu-cto-sauvik-banerjjee-quits-71285.html",
    text: "Tata Neu CTO Sauvik Banerjjee quits",
  },
  {
    "#": 23,
    date: "Aug 5, 2022",
    Source: "News Portal",
    "Channel Name": "au.sports.yahoo.com",
    img: "/yahoosport.png",
    url: "https:/au.sports.yahoo.com/rezolve-appoints-sauvik-banerjjee-global-113000405.html",
    text: "Rezolve Appoints Sauvik Banerjjee as Global CEO of Products, Technology, and Digital Services",
  },
  {
    "#": 24,
    date: "Jul 29, 2022",
    Source: "News Portal",
    "Channel Name": "techshotsapp.com",
    img: "/techShots.png",
    url: "https:/techshotsapp.com/people/cto-sauvik-banerjjee-quits-tata-neu-four-months-after-launch",
    text: "CTO Sauvik Banerjjee quits Tata Neu four months after launch",
    description:
      'Sauvik Banerjee, the CTO and founding member of Tata Neu, has left the Tata Group\'s online venture. His departure occurs only four months after the much-hyped "super app" was introduced by the Mumbai-based company in April. The IPL, for which Neu was the key sponsor, served as the backdrop for its marketing campaign upon inception. Banerjjee joined the Tata Group in 2016 as CTO of Tata Cliq. He relocated to Tata Digital in 2019 and has since worked with the core group.',
  },
  {
    "#": 25,
    date: "Aug 06, 2022",
    Source: "News Portal",
    "Channel Name": "officenewz.com",
    img: "/officenewz.png",
    url: "https:/www.officenewz.com/2022/08/06/tata-neu-cto-sauvik-banerjjee-quits-within-months-of-app-launch/",
    text: "Tata Neu CTO Sauvik Banerjjee quits within months of app launch",
  },
  {
    "#": 26,
    date: "Jul 31, 2022",
    Source: "News Portal",
    "Channel Name": "trak.in",
    img: "/trak.png",
    url: "https:/trak.in/tags/business/2022/07/31/tata-neu-cto-quits-within-4-months-of-super-app-launch-whats-the-reason-is-tata-neu-a-failure/",
    text: "Tata Neu CTO Quits Within 4-Months Of ‘Super App’ Launch: What’s The Reason? Is Tata Neu A Failure?",
  },
  {
    "#": 27,
    date: "Dec 1, 2018",
    Source: "News Portal",
    "Channel Name": "blog.sibmpune.edu.in",
    img: "/sibmpune.png",
    url: "https:/blog.sibmpune.edu.in/leadership-talk-tata-industries/",
    text: "Leadership Talk by Mr. Sauvik Banerjjee, VP – Tata Industries, CTO TataCLiQ",
  },
  {
    "#": 28,
    date: "Sep 19, 2017",
    Source: "News Portal",
    "Channel Name": "indiaretailing.com",
    img: "/retailing.png",
    url: "https:/www.indiaretailing.com/2017/09/19/sauvik-banerjjee-cto-tatacliq/",
    text: "Sauvik Banerjjee, CTO, TataCLiQ",
  },
  {
    "#": 29,
    date: "Nov 25, 2020",
    Source: "News Portal",
    img: "/medium.png",
    "Channel Name": "medium.com",
    url: "https:/medium.com/rohit-lalwani/empathy-in-digital-era-with-sauvik-banerjjee-521b02afae0c",
    text: "Empathy in Digital Era with Sauvik Banerjjee",
  },
  {
    "#": 30,
    date: "Apr 27, 2017",
    Source: "News Portal",
    img: "/e4m.png",
    "Channel Name": "exchange4media.com",
    url: "https:/www.exchange4media.com/digital-news/tatacliq.com-strengthens-leadership-team-with-sauvik-banerjjeekishore-mardikarand-behram-sabawala-68573.html",
    text: "TataCLiQ.com strengthens leadership team with Sauvik Banerjjee, Kishore Mardikar, and Behram Sabawala",
  },
];

const newsData = [
  {
    text: "Sauvik Banerjjee Leads Rezolve Ai as President & CDO",
    img: "/Rediff Logo.jpg",
    description: `Sauvik Banerjjee Leads Rezolve Ai as President & CDO`,
    date: "July 01, 2025",
    url: "https://money.rediff.com/news/market/sauvik-banerjjee-leads-rezolve-ai-as-president-cdo/29433220250701",
  },
  {
    text: "Sauvik Banerjjee to lead Rezolve Ai as President chief digital officer",
    img: "/The Week Logo.jpg",
    description: `Sauvik Banerjjee to lead Rezolve Ai as President chief digital officer`,
    date: "July 01, 2025",
    url: "https://www.theweek.in/wire-updates/business/2025/07/01/dcm123-biz-resolve-ai-appt.html",
  },
  {
    text: "UK-based Rezolve Ai appoints Sauvik Banerjjee as global CEO of products, tech, digital services - The Economic Times",
    img: "/The Economic Times Tech Logo.jpg",
    description: `UK-based Rezolve Ai appoints Sauvik Banerjjee as global CEO of products, tech, digital services - The Economic Times`,
    date: "July 01, 2025",
    url: "https://economictimes.indiatimes.com/tech/artificial-intelligence/uk-based-rezolve-ai-appoints-sauvik-banerjjee-as-global-ceo-of-products-tech-digital-services/articleshow/122186791.cms",
  },
  {
    text: "Rezolve Ai Establishes Global Professional Services Division Amid Surging Demand in $500 Billion Enterprise AI Market",
    img: "/Yahoo Finance Logo.jpg",
    description: `Rezolve Ai Establishes Global Professional Services Division Amid Surging Demand in $500 Billion Enterprise AI Market`,
    date: "June 26, 2025",
    url: "https://finance.yahoo.com/news/rezolve-ai-establishes-global-professional-120000679.html",
  },
  {
    text: "Rezolve Appoints Sauvik Banerjjee as Global CEO of Products, Technology, and Digital Services",
    img: "/bloomberg.png",
    description: `Rezolve Appoints Sauvik Banerjjee as Global CEO of Products, Technology, and Digital Services`,
    date: "August 08, 2022",
    url: "https://www.bloomberg.com/press-releases/2022-08-08/rezolve-appoints-sauvik-banerjjee-as-global-ceo-of-products-technology-and-digital-services",
  },
  {
    text: "The Big Picture: Sauvik Banerjjee at Tata Digital and Anand Chandrasekaran..",
    img: "/fobes.png",
    description: `Our guests today are Sauvik Banerjjee, founding CTO of Tata Digital, and Anand Chandrasekaran, co-founder and CTO of Mad Street Den, whose AI platform blox.ai plays an important role in the personalisation features of the Tata Group's new consumer app.`,
    date: "June 09, 2022",
    url: "https://www.forbesindia.com/audio/forbes-india-daily-tech-conver-sation/the-big-picture-sauvik-banerjjee-at-tata-digital-and-anand-chandrasekaran-at-mad-street-den-on-whither-personalisation/77129",
  },
  {
    text: `Former Tata Neu CTO Sauvik Banerjjee joins Rezolve `,
    img: "/tet.png",
    description: `UK-based mobile commerce and engagement company, Rezolve has appointed former Tata Neu chief technology officer (CTO) Sauvik Banerjjee as its global chief executive of products, technology and digital services.`,
    date: "August 09, 2022",
    url: "https://economictimes.indiatimes.com/tech/technology/former-tata-neu-cto-sauvik-banerjjee-joins-rezolve/articleshow/93448437.cms?from=mdr",
  },
  {
    text: "Sauvik Banerjjee, former Tata Digital CTO, joins UK's Rezolve",
    img: "/bussiness.png",
    description: `Sauvik Banerjjee, who recently resigned from Tata Digital as the founding CTO, has joined Rezolve, a UK-based mobile commerce and engagement company, as its global Chief Executive Officer of products, technology, and digital services.`,
    date: "August 09, 2022",
    url: "https://economictimes.indiatimes.com/tech/technology/former-tata-neu-cto-sauvik-banerjjee-joins-rezolve/articleshow/93448437.cms?from=mdr",
  },

  {
    text: " Tata Neu's CTO Sauvik Banerjjee has quit for personal reasons, according to Tata Digital.",
    img: "/msn.png",
    description: `Tata Neu CTO Sauvik Banerjjee quits within months of app launch`,
    date: "August 05, 2022",
    url: "https://www.newsdrum.in/business/tata-neu-cto-sauvik-banerjjee-quits-71285.html",
  },
];

export { newsData, newsData2 };
